language: csharp
solution: Moqzilla.sln
sudo: false
addons:
  apt:
    packages:
    - nunit-console
script:
  - xbuild /p:Configuration=Debug Moqzilla.sln
before_script:
  - nuget restore Moqzilla.sln
after_script:
  - nunit-console Moqzilla.Test/bin/Debug/net45/Moqzilla.Test.dll
 