language: csharp
solution: src/Moqzilla.sln
sudo: false
addons:
  apt:
    packages:
      - nunit-console
      - libunwind8
before_install:
  - chmod a+x "$TRAVIS_MSBUILD_BIN"/msbuild-prepare
  - msbuild-prepare
script:
  - msbuild /p:Configuration=Debug src/Moqzilla.sln
before_script:
  - nuget restore src/Moqzilla.sln
after_script:
  - nunit-console src/Moqzilla.Test/bin/Debug/net45/Moqzilla.Test.dll
